package org.layeredencryption.pairing

import org.layeredencryption.CryptoProvider

/**
 * A pairing code (docs/Protocol.md §6.1–§6.2).
 *
 * Twenty-four characters drawn uniformly from a 35-symbol alphabet (A–Z without `O`, plus 0–9),
 * generated by the platform CSPRNG and shown as six groups of four, three groups to a line:
 *
 * ```
 * K7M4-F2X9-4BQR
 * 1TZP-9WVC-3HND
 * ```
 *
 * Space 35²⁴ ≈ 1.14 × 10³⁷ ≈ **123 bits**, which puts offline recovery permanently out of reach.
 * That matters because a captured pairing MAC *is* an offline verifier: an attacker running its own
 * handshake leg knows that leg's handshake key, so only the code-derived secret is unknown and
 * candidates can be tested locally, outside any attempt limit. The length is what closes that,
 * rather than the three-attempt limit, which only ever constrained online guessing.
 *
 * The code is expected to arrive by QR; typing it is the fallback for when a camera will not
 * cooperate, which is why length was traded for margin rather than for convenience.
 *
 * ### Why the alphabet is 35 symbols and not 36 folded to 35
 * `O` is **never generated**. An earlier version drew uniformly from all 36 alphanumerics and then
 * folded `O` to `0` when canonicalising, which is not the same thing: it made `0` twice as likely
 * as every other symbol (measured at 0.0552 against 0.0281), dropping min-entropy well below the
 * documented figure and making the best few guesses far better than uniform. Sampling the canonical
 * alphabet directly is the only way the entropy claim above is true.
 *
 * The `O` → `0` fold survives on the *input* side, where it costs nothing and forgives a user who
 * reads a `0` as an `O`.
 *
 * Remaining confusability is handled at **display** time rather than by shrinking the alphabet
 * further: uppercase Atkinson Hyperlegible Mono, with letters and digits in different theme colours
 * (§6.2). Every other classic confusable pair — I/1, L/1, S/5, B/8, Z/2, G/6 — is letter-vs-digit,
 * so the class colouring disambiguates it.
 *
 * Two forms matter:
 * - [display] — the exact generated characters, for showing to the user.
 * - [canonical] — the folded, separator-free form `S` used to derive the rendezvous id and the
 *   code-secret. Both devices independently canonicalise (the inviter its own code, the joiner what
 *   the user typed); folding is idempotent and confusable-insensitive, so they agree.
 */
class PairingCode private constructor(
    val display: String,
    val canonical: String,
) {
    /** One line's worth of groups, e.g. `K7M4-F2X9-4BQR`. Two lines make the whole code. */
    val lines: List<String> get() = groups.chunked(GROUPS_PER_LINE).map { it.joinToString("-") }

    /** The user-facing grouped form on a single line, e.g. `K7M4-F2X9-4BQR-1TZP-9WVC-3HND`. */
    val formatted: String get() = groups.joinToString("-")

    private val groups: List<String> get() = display.chunked(GROUP_SIZE)

    companion object {
        const val LENGTH = 24
        const val GROUP_SIZE = 4
        const val GROUPS_PER_LINE = 3

        /** A–Z without `O`, then 0–9. Exactly 35 symbols, sampled directly. */
        private const val ALPHABET = "ABCDEFGHIJKLMNPQRSTUVWXYZ0123456789"
        private const val REJECT_THRESHOLD = 245 // 35 * 7; reject 245..255 to keep the draw uniform

        /** Generates a fresh code from the platform CSPRNG using rejection sampling for uniformity. */
        fun generate(provider: CryptoProvider): PairingCode {
            val builder = StringBuilder(LENGTH)
            while (builder.length < LENGTH) {
                val draw = provider.randomBytes(1)[0].toInt() and 0xFF
                if (draw < REJECT_THRESHOLD) builder.append(ALPHABET[draw % ALPHABET.length])
            }
            return of(builder.toString())
        }

        /** Wraps an already-known set of display characters (e.g. under test). */
        fun of(display: String): PairingCode {
            val canonical = canonicalise(display)
                ?: throw IllegalArgumentException("Not a valid $LENGTH-character pairing code: $display")
            return PairingCode(display = display.uppercase(), canonical = canonical)
        }

        /**
         * Folds raw user input into the canonical form `S`, or returns `null` if it is not a valid
         * code. Strips the documented separators — hyphens and whitespace — uppercases, then folds
         * the one forgiven pair: O→0. Any *other* character rejects the whole input rather than
         * being silently dropped: an earlier version stripped everything non-alphanumeric, which
         * made unboundedly many strings canonicalise to the same code.
         */
        fun canonicalise(raw: String): String? {
            val folded = StringBuilder(LENGTH)
            for (char in raw.uppercase()) {
                if (char == '-' || char.isWhitespace()) continue // the documented separators
                val mapped = fold(char) ?: return null
                folded.append(mapped)
            }
            return if (folded.length == LENGTH) folded.toString() else null
        }

        private fun fold(char: Char): Char? = when (char) {
            'O' -> '0' // the only forgiven confusable; I/L/1 stay distinct (colour + font disambiguate)
            in 'A'..'N', in 'P'..'Z', in '0'..'9' -> char // the 35-symbol alphabet ('O' folded above)
            else -> null // not a code character
        }
    }
}
