package org.layeredencryption.pairing

import org.layeredencryption.CryptoProvider

/**
 * A pairing code (docs/Protocol.md §6.1–§6.2).
 *
 * Six characters from the full 36-char alphabet (A–Z, 0–9), generated by the platform CSPRNG and
 * shown grouped as `K7M-0F2`.
 *
 * Confusability is handled at **display** time, not by shrinking the alphabet: uppercase Atkinson
 * Hyperlegible Mono, with letters and digits in different theme colours (§6.2). Every classic
 * confusable pair — I/1, L/1, S/5, B/8, Z/2, G/6 — is letter-vs-digit, so the class colouring
 * disambiguates it and all 36 characters stay usable.
 *
 * One exception is folded in verification: **{0, O}**, the single pair where the shapes stay close
 * enough to be worth forgiving. `1`, `I` and `L` are all distinct and must be entered as shown.
 * Effective space 35⁶ ≈ 1.84 bn ≈ **30.8 bits**.
 *
 * Two forms matter:
 * - [display] — the exact generated characters, for showing to the user.
 * - [canonical] — the folded, separator-free form `S` used to derive the rendezvous id and the
 *   code-secret. Both devices independently canonicalise (the inviter its own code, the joiner what
 *   the user typed); folding is idempotent and confusable-insensitive, so they agree.
 */
class PairingCode private constructor(
    val display: String,
    val canonical: String,
) {
    /** The user-facing grouped form, e.g. `K7M-0F2`. */
    val formatted: String get() = display.substring(0, HALF) + "-" + display.substring(HALF)

    companion object {
        const val LENGTH = 6
        private const val HALF = 3
        private const val ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789" // 36 chars
        private const val REJECT_THRESHOLD = 252 // 36 * 7; reject 252..255 to keep the draw uniform

        /** Generates a fresh code from the platform CSPRNG using rejection sampling for uniformity. */
        fun generate(provider: CryptoProvider): PairingCode {
            val builder = StringBuilder(LENGTH)
            while (builder.length < LENGTH) {
                val draw = provider.randomBytes(1)[0].toInt() and 0xFF
                if (draw < REJECT_THRESHOLD) builder.append(ALPHABET[draw % ALPHABET.length])
            }
            return of(builder.toString())
        }

        /** Wraps an already-known set of display characters (e.g. under test). */
        fun of(display: String): PairingCode {
            val canonical = canonicalise(display)
                ?: throw IllegalArgumentException("Not a valid $LENGTH-character pairing code: $display")
            return PairingCode(display = display.uppercase(), canonical = canonical)
        }

        /**
         * Folds raw user input into the canonical form `S`, or returns `null` if it is not a valid
         * code. Strips separators/whitespace, uppercases, then folds the one forgiven pair: O→0.
         */
        fun canonicalise(raw: String): String? {
            val folded = StringBuilder(LENGTH)
            for (char in raw.uppercase()) {
                val mapped = fold(char) ?: continue // skip separators/whitespace
                if (mapped !in ALPHABET) return null
                folded.append(mapped)
            }
            return if (folded.length == LENGTH) folded.toString() else null
        }

        private fun fold(char: Char): Char? = when (char) {
            'O' -> '0' // the only forgiven confusable; I/L/1 stay distinct (colour + font disambiguate)
            in 'A'..'Z', in '0'..'9' -> char
            else -> null // hyphens, spaces, anything else is dropped
        }
    }
}
