package org.layeredencryption

import kotlinx.coroutines.async
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.test.runTest
import org.layeredencryption.identity.DeviceKeys
import org.layeredencryption.pairing.PairingCode
import org.layeredencryption.pairing.PairingFerry
import java.io.File
import java.security.SecureRandom
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Runs a real ceremony, records it, checks the recording leaks nothing, and writes the inspector
 * page from what actually happened.
 *
 * The point of doing this as a test rather than a tool: the page cannot drift from the library,
 * because it is generated by running the library, and the same run asserts the properties the
 * page claims. If the protocol changes, this either regenerates or fails.
 *
 * Output lands in `lep/build/inspector/index.html`; open it from disk.
 */
class InspectorTest {

    /** A ceremony is only reproducible if every key and nonce comes from a known seed. */
    private fun seededProvider(seed: String) =
        BouncyCastleCryptoProvider(SecureRandom.getInstance("SHA1PRNG").apply { setSeed(seed.encodeToByteArray()) })

    private class Pipe(
        private val incoming: Channel<ByteArray>,
        private val outgoing: Channel<ByteArray>,
    ) : FrameChannel {
        override suspend fun send(frame: ByteArray) = outgoing.send(frame)
        override suspend fun receive(): ByteArray = incoming.receive()
        override fun close() { outgoing.close() }
    }

    private fun pipePair(): Pair<FrameChannel, FrameChannel> {
        val toJoiner = Channel<ByteArray>(Channel.UNLIMITED)
        val toInviter = Channel<ByteArray>(Channel.UNLIMITED)
        return Pipe(toInviter, toJoiner) to Pipe(toJoiner, toInviter)
    }

    /** Everything the recorder was told, kept in order. */
    private class Collector : ProtocolRecorder, InspectorPage.HasMessages {
        val messages = mutableListOf<RecordedMessage>()
        val notes = mutableListOf<String>()
        val derivations = mutableListOf<Triple<String, String, String>>()
        var succeeded = false
        var detail = ""

        override fun message(step: RecordedMessage) { messages += step }
        override fun recordedMessages(): List<RecordedMessage> = messages
        override fun derivation(label: String, from: String, produces: String) { derivations += Triple(label, from, produces) }
        override fun agreedBytes(name: String, bytes: ByteArray, composition: List<RecordedField>) = Unit
        override fun note(text: String) { notes += text }
        override fun outcome(succeeded: Boolean, detail: String) { this.succeeded = succeeded; this.detail = detail }
    }

    private class Recorded(
        val collector: Collector,
        val masterKey: ByteArray,
        val inviterKeys: DeviceKeys,
        val joinerKeys: DeviceKeys,
        val sas: String,
    )

    private suspend fun recordCeremony(): Recorded {
        val provider = seededProvider("inspector-fixture-v1")
        val collector = Collector()
        val code = PairingCode.generate(provider)

        val inviterKeys = DeviceKeys.generate(provider)
        val joinerKeys = DeviceKeys.generate(provider)

        val (inviterChannel, joinerChannel) = pipePair()
        // Only the inviter's side is wrapped: one recorder sees every frame in both directions,
        // because every frame crosses this channel exactly once.
        val recording = RecordingChannel(inviterChannel, collector, "inviter", provider)

        var sas = ""
        val joinerSide = kotlinx.coroutines.CoroutineScope(kotlin.coroutines.EmptyCoroutineContext)
            .async { PairingFerry.runJoiner(joinerChannel, provider, joinerKeys, code, confirmSas = { true }) }
        val inviterKey = PairingFerry.runInviter(recording, provider, inviterKeys, code, confirmSas = { shown -> sas = shown; true }).masterKey
        val joinerKey = joinerSide.await().masterKey

        assertContentEquals(inviterKey, joinerKey, "both sides must end with the same master key")
        collector.outcome(true, "paired; both sides hold the same master key")
        return Recorded(collector, inviterKey, inviterKeys, joinerKeys, sas)
    }

    @Test
    fun `a recorded ceremony contains no key material`() = runTest {
        val run = recordCeremony()
        val recording = InspectorPage.json(run.collector, run.sas)

        // The recorder sees only what crossed the wire, so this should hold structurally. Assert
        // it anyway, with the run's real secrets, because "should hold structurally" is exactly
        // the kind of claim that quietly stops being true.
        val secrets = mapOf(
            "master key" to run.masterKey,
            "inviter signing private key" to run.inviterKeys.signingPrivateKey,
            "inviter X25519 private key" to run.inviterKeys.x25519IdentityPrivateKey,
            "joiner signing private key" to run.joinerKeys.signingPrivateKey,
            "joiner X25519 private key" to run.joinerKeys.x25519IdentityPrivateKey,
        )
        for ((name, secret) in secrets) {
            assertFalse(recording.contains(secret.toHexString()), "$name appears in the recording")
            assertFalse(recording.contains(secret.toHexString().uppercase()), "$name appears in the recording")
        }
    }

    @Test
    fun `the recording describes the whole ceremony in order`() = runTest {
        val run = recordCeremony()
        val steps = run.collector.messages

        assertEquals(
            listOf(
                "SuiteOffer", "SuiteAccept",
                "InviterHello", "JoinerResponse", "InviterConfirm", "SasConfirmed", "InviterComplete",
            ),
            steps.map { it.name },
            "every frame should be decoded and attributed, in the order the protocol sends them",
        )
        assertEquals(listOf("inviter", "joiner", "inviter", "joiner", "inviter", "joiner", "inviter"), steps.map { it.from })
        assertTrue(steps.all { it.sizeBytes > 0 })
        assertTrue(run.collector.succeeded)
    }

    @Test
    fun `the inspector page is written from the run`() = runTest {
        val run = recordCeremony()

        val output = File("build/inspector/index.html")
        output.parentFile.mkdirs()
        output.writeText(InspectorPage.render(run.collector, run.sas))

        assertTrue(output.length() > 4_000, "the page should carry the whole recording")
        // The page is the recording plus a renderer: if the ceremony changes, this file changes.
        assertTrue(output.readText().contains("InviterComplete"))
        println("Ceremony inspector written to ${output.absolutePath}")
    }
}
