package org.layeredencryption

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.async
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.test.runTest
import org.layeredencryption.envelope.EpochKeys
import org.layeredencryption.envelope.LaneEnvelope
import org.layeredencryption.identity.DeviceKeys
import org.layeredencryption.invite.AsyncInviteState
import org.layeredencryption.invite.AsyncRendezvous
import org.layeredencryption.invite.InviteBundle
import org.layeredencryption.invite.InviteLink
import org.layeredencryption.invite.PendingInvite
import org.layeredencryption.membership.MembershipLog
import org.layeredencryption.membership.MembershipOp
import org.layeredencryption.membership.WrappedKeys
import org.layeredencryption.pairing.Inviter
import org.layeredencryption.pairing.Joiner
import org.layeredencryption.pairing.PairingCode
import org.layeredencryption.pairing.PairingFerry
import org.layeredencryption.storage.FileBackedFreshnessStore
import org.layeredencryption.storage.FileBackedInviteStore
import java.io.File
import java.nio.file.Files
import java.security.SecureRandom
import kotlin.coroutines.EmptyCoroutineContext
import kotlin.test.Test

/**
 * Generates the frozen Suite 1 compatibility fixtures committed as `Suite1Fixtures.kt` in
 * commonTest (docs/POST_QUANTUM_HARDENING_AND_MIGRATION.md, plan §1: "freeze compatibility
 * before refactoring").
 *
 * Inert by default: the test body returns immediately unless `LEP_GENERATE_FIXTURES=1` is set,
 * so CI never regenerates anything. To regenerate (which should happen essentially never — the
 * committed fixtures ARE the freeze):
 *
 * ```
 * LEP_GENERATE_FIXTURES=1 ./gradlew :lep:jvmTest --tests '*Suite1FixtureGenerator*'
 * ```
 *
 * The output lands in `lep/build/generated-fixtures/Suite1Fixtures.kt`; copy it over the
 * committed file. Every key and nonce comes from one seeded provider (the InspectorTest
 * pattern), so a regeneration from the same seed on the same provider version reproduces the
 * same artifacts — but the committed bytes, not the seed, are the contract. Regenerating
 * *replaces* the freeze and defeats its purpose unless the old fixtures provably still pass.
 */
class Suite1FixtureGenerator {

    /** Every key and nonce below comes from this seed, in the documented draw order. */
    private fun seededProvider() = BouncyCastleCryptoProvider(
        SecureRandom.getInstance("SHA1PRNG").apply { setSeed(SEED.encodeToByteArray()) },
    )

    private class CapturingChannel(
        private val incoming: Channel<ByteArray>,
        private val outgoing: Channel<ByteArray>,
        val frames: MutableList<ByteArray>,
    ) : FrameChannel {
        override suspend fun send(frame: ByteArray) {
            frames += frame.copyOf()
            outgoing.send(frame)
        }
        override suspend fun receive(): ByteArray = incoming.receive().also { frames += it.copyOf() }
        override fun close() { outgoing.close() }
    }

    @Test
    fun generate() = runTest {
        if (System.getenv("LEP_GENERATE_FIXTURES") == null) return@runTest
        val provider = seededProvider()
        val out = StringBuilder()

        out.appendLine(
            """
            |package org.layeredencryption
            |
            |/**
            | * Frozen Suite 1 (LEP_HYBRID_2026) compatibility fixtures: real artifacts produced by the
            | * shipped implementation, committed byte for byte (docs/POST_QUANTUM_HARDENING_AND_MIGRATION.md §1).
            | *
            | * These bytes are the compatibility contract. `Suite1CompatTest` proves the current code
            | * still parses, verifies, decrypts, and byte-identically re-serialises them;
            | * `Suite1ReproductionTest` proves the deterministic operations (signatures over fixed keys)
            | * still reproduce the same bytes. A change that turns any of these tests red has changed
            | * the protocol, whatever it was called in the commit message.
            | *
            | * GENERATED by Suite1FixtureGenerator (seed "$SEED") — do not hand-edit hex.
            | */
            |@Suppress("SpellCheckingInspection", "LargeClass")
            |internal object Suite1Fixtures {
            |
            |    fun hex(s: String): ByteArray =
            |        ByteArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16).toByte() }
            |
            |    /** Runtime concatenation: keeps every literal far below the JVM's 64 KB string-constant cap. */
            |    private fun concat(vararg parts: String): String = parts.joinToString("")
            """.trimMargin(),
        )

        // ── 1. Device identities ──────────────────────────────────────────────────────────────
        val founder = DeviceKeys.generate(provider)
        val member = DeviceKeys.generate(provider)
        out.section("Device identities: serialised public identity + the private halves needed to re-sign/unwrap.")
        out.bytes("founderIdentity", founder.identity.serialise())
        out.bytes("founderSigningPrivateKey", founder.signingPrivateKey)
        out.bytes("founderX25519PrivateKey", founder.x25519IdentityPrivateKey)
        out.bytes("founderXWingPrivateKey", founder.xWingPrivateKey)
        out.bytes("memberIdentity", member.identity.serialise())
        out.bytes("memberSigningPrivateKey", member.signingPrivateKey)
        out.bytes("memberX25519PrivateKey", member.x25519IdentityPrivateKey)
        out.bytes("memberXWingPrivateKey", member.xWingPrivateKey)

        // ── 2. Membership log: genesis ADD + ADD + ROTATE + REVOKE ────────────────────────────
        val rotateKey = provider.randomBytes(32)
        val revokeKey = provider.randomBytes(32)
        val log = MembershipLog.found(provider, founder.identity, founder.signingKeyPair)
            .append(provider, MembershipOp.ADD, member.identity, wrappedKeys = null, signer = founder.signingKeyPair)
            .rotate(provider, rotateKey, signer = founder)
            .revoke(provider, member.identity, revokeKey, signer = founder.signingKeyPair)
        out.section(
            "Membership log: genesis ADD(founder) + ADD(member) + ROTATE + REVOKE(member), all founder-signed. " +
                "Exercises every op code, the wrappedFlag byte both ways, and both rotation-carrying entry kinds.",
        )
        out.bytes("membershipLog", log.serialise())
        log.entries.forEachIndexed { index, entry ->
            out.bytes("membershipEntryHash$index", entry.hash(provider))
        }
        out.bytes("membershipRotateKey", rotateKey)
        out.bytes("membershipRevokeKey", revokeKey)

        // ── 3. Standalone wrapped keys (two recipients) ───────────────────────────────────────
        val wrappedMasterKey = provider.randomBytes(32)
        val wrappedBlob = WrappedKeys.wrapFor(provider, listOf(founder.identity, member.identity), wrappedMasterKey)
        out.section("Standalone WrappedKeys blob: one 32-byte key sealed for founder and member.")
        out.bytes("wrappedKeysBlob", wrappedBlob)
        out.bytes("wrappedMasterKey", wrappedMasterKey)

        // ── 4. Lane envelope v2 + epoch keys ──────────────────────────────────────────────────
        val envelopeKey = provider.randomBytes(32)
        val envelope = LaneEnvelope.seal(
            provider, EpochKeys.founding(envelopeKey),
            contextId = ENVELOPE_CONTEXT, lane = ENVELOPE_LANE, seq = ENVELOPE_SEQ,
            plaintext = ENVELOPE_PLAINTEXT.encodeToByteArray(),
        )
        out.section("Lane envelope, version 2, epoch 0, and the key that opens it.")
        out.appendLine("    const val envelopeContextId = \"$ENVELOPE_CONTEXT\"")
        out.appendLine("    const val envelopeLane = \"$ENVELOPE_LANE\"")
        out.appendLine("    const val envelopeSeq = $ENVELOPE_SEQ")
        out.appendLine("    const val envelopePlaintext = \"$ENVELOPE_PLAINTEXT\"")
        out.bytes("envelopeBytes", envelope.serialise())
        out.bytes("envelopeKey", envelopeKey)

        val epochKey0 = provider.randomBytes(32)
        val epochKey1 = provider.randomBytes(32)
        out.section("Epoch keys: two epochs, ascending — fully re-encodable from the parts.")
        out.bytes("epochKeysBytes", EpochKeys.founding(epochKey0).withNextEpoch(epochKey1).serialise())
        out.bytes("epochKey0", epochKey0)
        out.bytes("epochKey1", epochKey1)

        // ── 5. Async invite: link + bundle ────────────────────────────────────────────────────
        val inviteSecret = provider.randomBytes(InviteLink.SECRET_SIZE)
        val link = InviteLink.create(provider, inviteSecret, founder.identity)
        val ridAsync = AsyncRendezvous.id(provider, inviteSecret)
        val inviteKem = XWing.generateKeyPair(provider)
        val bundle = InviteBundle.build(
            provider, inviteKem.publicKey, founder.identity,
            expiryEpochSeconds = INVITE_EXPIRY, ridAsync = ridAsync, signer = founder.signingKeyPair,
        )
        out.section("Async invite: A2 link, rid_async, and the signed pre-published bundle.")
        out.appendLine("    const val inviteLinkUrl = \"${link.url()}\"")
        out.appendLine("    const val inviteExpiryEpochSeconds = ${INVITE_EXPIRY}L")
        out.bytes("inviteSecret", inviteSecret)
        out.bytes("inviteRidAsync", ridAsync)
        out.bytes("inviteKemPublicKey", inviteKem.publicKey)
        out.bytes("inviteKemPrivateKey", inviteKem.privateKey)
        out.bytes("inviteBundle", bundle.serialise())

        // ── 6. Full pairing ceremony: all five wire frames ────────────────────────────────────
        val code = PairingCode.generate(provider)
        val inviter = Inviter(provider, founder, code)
        val joiner = Joiner(provider, member, code)
        val toJoiner = Channel<ByteArray>(Channel.UNLIMITED)
        val toInviter = Channel<ByteArray>(Channel.UNLIMITED)
        val frames = mutableListOf<ByteArray>()
        // Only the inviter's side captures: every frame crosses it exactly once, in protocol order.
        val inviterChannel = CapturingChannel(toInviter, toJoiner, frames)
        val joinerChannel = object : FrameChannel {
            override suspend fun send(frame: ByteArray) = toInviter.send(frame)
            override suspend fun receive(): ByteArray = toJoiner.receive()
            override fun close() { toInviter.close() }
        }
        val joinerSide = CoroutineScope(EmptyCoroutineContext)
            .async { PairingFerry.runJoiner(joinerChannel, joiner, confirmSas = { true }) }
        PairingFerry.runInviter(inviterChannel, inviter, confirmSas = { true })
        joinerSide.await()
        check(frames.size == 5) { "Expected the 5 ceremony frames, captured ${frames.size}" }
        out.section("Pairing ceremony frames, in protocol order (founder invites member into a fresh calendar).")
        out.bytes("pairingInviterHello", frames[0])
        out.bytes("pairingJoinerResponse", frames[1])
        out.bytes("pairingInviterConfirm", frames[2])
        out.bytes("pairingSasConfirmed", frames[3])
        out.bytes("pairingInviterComplete", frames[4])

        // ── 7. Sealed state files, both store kinds ───────────────────────────────────────────
        val storeKey = provider.randomBytes(32)
        val storeMasterKey = provider.randomBytes(32)
        val storeDir = Files.createTempDirectory("suite1-fixtures")
        val inviteStorePath = storeDir.resolve("invite.store")
        FileBackedInviteStore.withoutRollbackDetection(inviteStorePath, provider, storeKey).put(
            PendingInvite(
                ridAsync = ridAsync,
                secret = inviteSecret,
                inviteXWingPublicKey = inviteKem.publicKey,
                inviteXWingPrivateKey = inviteKem.privateKey,
                masterKey = storeMasterKey,
                expiryEpochSeconds = INVITE_EXPIRY,
                state = AsyncInviteState.PENDING,
            ),
        )
        val freshnessStorePath = storeDir.resolve("freshness.store")
        FileBackedFreshnessStore.withoutRollbackDetection(freshnessStorePath, provider, storeKey)
            .accept(ENVELOPE_CONTEXT, ENVELOPE_LANE, seq = ENVELOPE_SEQ, epoch = 1)
        out.section(
            "Sealed state files at revision 1, both store kinds, under one at-rest key. " +
                "Not byte-reproducible (fresh cascade nonces) — the fixture proves load + AAD binding + decrypt.",
        )
        out.bytes("sealedInviteStoreFile", Files.readAllBytes(inviteStorePath))
        out.bytes("sealedFreshnessStoreFile", Files.readAllBytes(freshnessStorePath))
        out.bytes("sealedStoreKey", storeKey)
        out.bytes("sealedStoreMasterKey", storeMasterKey)
        storeDir.toFile().deleteRecursively()

        out.appendLine("}")

        val target = File("build/generated-fixtures/Suite1Fixtures.kt")
        target.parentFile.mkdirs()
        target.writeText(out.toString())
        println("Suite 1 fixtures written to ${target.absolutePath}")
        println("Copy over lep/src/commonTest/kotlin/org/layeredencryption/Suite1Fixtures.kt to commit the freeze.")
    }

    // ── Emission helpers ──────────────────────────────────────────────────────────────────────

    private fun StringBuilder.section(comment: String) {
        appendLine()
        appendLine("    // $comment")
    }

    /**
     * Emits one fixture as a chunked-hex function pair. Chunks stay well under the JVM's 64 KB
     * string-constant limit, and each fixture's `concat` call sits in its own method so no
     * single method (`<clinit>` included) accumulates the whole corpus.
     */
    private fun StringBuilder.bytes(name: String, value: ByteArray) {
        val hex = value.toHexString()
        appendLine("    fun $name(): ByteArray = hex(${name}Hex())")
        appendLine("    private fun ${name}Hex(): String = concat(")
        for (chunk in hex.chunked(96)) appendLine("        \"$chunk\",")
        appendLine("    )")
    }

    private companion object {
        const val SEED = "lep-suite1-fixtures-v2"
        const val ENVELOPE_CONTEXT = "ctx-suite1-fixture"
        const val ENVELOPE_LANE = "device-1"
        const val ENVELOPE_SEQ = 7
        const val ENVELOPE_PLAINTEXT = "suite1 frozen envelope"
        const val INVITE_EXPIRY = 1_924_992_000L
    }
}
